name: CI
on: push

jobs:
  presubmit:
    runs-on: generic-linux
    container: docker.artifactory.rbx.com/python:3

    steps:
    - uses: actions/checkout@v2

    - name: Install linters
      run: |
        pip3 install black==22.8.0

    - name: Check files are formatted
      run: |
        black --required-version 22.8.0 --config pyproject.toml finetune --check

    - name: Run unit tests
      run: |
        pip3 install -r finetune/requirements.txt
        finetune/run_tests.sh
